
spring:
    datasource:
        url: jdbc:mysql://127.0.0.1:3306/abc?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8&allowMultiQueries=true
        username: root
        password: 12345678
        driver-class-name: com.mysql.cj.jdbc.Driver
    redis:
        database: 0
        host: 127.0.0.1
        port: 6379
        #   password: 123456
        pool:
            min-idle: 1 # 连接池中的最小空闲连接
            max-idle: 300 # 连接池中的最大空闲连接
            maxActive: 600 # 连接池最大连接数（使用负值表示没有限制）
            maxWait: 10 # 连接池最大阻塞等待时间（使用负值表示没有限制）
            timeout: 1000 # 连接超时时间（毫秒）
logging:
    config: classpath:logback.xml
    level:
        com.hl.magic: trace
mybatis:
    mapper-locations: classpath:mapper/*.xml
    type-aliases-package: com.project.demo.pojo.po
